[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B"]

[tool.ruff.isort]
known-first-party = ["pipeline"]
